// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMvUxYgauWNOYdW1kEq_1GONuay8NbzrM',
    appId: '1:486450919235:web:cb718789967edcba5721f6',
    messagingSenderId: '486450919235',
    projectId: 'janice-mynotes-flutter-project',
    authDomain: 'janice-mynotes-flutter-project.firebaseapp.com',
    storageBucket: 'janice-mynotes-flutter-project.appspot.com',
    measurementId: 'G-WKK4LZYER7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3lyCOXA9lpYIZD0vMLwYgkPVsZP7G5Dw',
    appId: '1:486450919235:android:ec0d4de7574b33835721f6',
    messagingSenderId: '486450919235',
    projectId: 'janice-mynotes-flutter-project',
    storageBucket: 'janice-mynotes-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArUVYGUNkJ0kJKIHYW2Sl7e6AqxAhBfQ4',
    appId: '1:486450919235:ios:f9d86586ca55bbcd5721f6',
    messagingSenderId: '486450919235',
    projectId: 'janice-mynotes-flutter-project',
    storageBucket: 'janice-mynotes-flutter-project.appspot.com',
    iosClientId: '486450919235-va8m21a21ccv05n9hc4vourjmhf38imj.apps.googleusercontent.com',
    iosBundleId: 'in.co.janice.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArUVYGUNkJ0kJKIHYW2Sl7e6AqxAhBfQ4',
    appId: '1:486450919235:ios:16fc64ccdb084be75721f6',
    messagingSenderId: '486450919235',
    projectId: 'janice-mynotes-flutter-project',
    storageBucket: 'janice-mynotes-flutter-project.appspot.com',
    iosClientId: '486450919235-mck8ek79dn9q4gtj1abq5rohh9k133rf.apps.googleusercontent.com',
    iosBundleId: 'in.co.janice.mynotes.RunnerTests',
  );
}
